# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'Precipitate' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Precipitate

  pod 'Alamofire', '4.8.0'
  pod 'Anchorage', '4.3.0'
  pod 'DateToolsSwift', '4.0.0'
  pod 'SwiftChart', '1.0.1'

  target 'PrecipitateTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PrecipitateUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == 'SwiftChart'
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.0'
            end
        end
    end
end

