# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Precipitate' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Precipitate

  pod 'Alamofire'
  pod 'Anchorage'
  pod 'DateToolsSwift'
  pod 'SwiftChart'

  target 'PrecipitateTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PrecipitateUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'Alamofire' || target.name == 'Anchorage'
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '3.2'
            end
        end
    end
end

