# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'
 inhibit_all_warnings!

target 'Precipitate' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Precipitate

  pod 'Alamofire', '4.8.1'
  pod 'Anchorage', '4.3.1'
  pod 'DateToolsSwift', '4.0.0'
  pod 'SwiftChart', :git => 'https://github.com/gpbl/SwiftChart'

  target 'PrecipitateTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PrecipitateUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'DateToolsSwift' || target.name == 'Alamofire' || target.name == 'SwiftChart'
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.2'
      end
    end
  end
end
